package com.practice.hibernate.hql;

import com.practice.hibernate.Certificate;
import com.practice.hibernate.Student;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

public class InputDataToDB {

    public static void insertDummyData() {

        Student student1 =
                new Student(1110, "Virat Kohli",
                        "New Delhi",
                        new Certificate("Batting MasterClass", "5 Years"));

        Student	student2	= new Student(1111,"Test1","City1",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student3	= new Student(1112,"Test2","City2",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student4	= new Student(1113,"Test3","City3",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student5	= new Student(1114,"Test4","City4",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student6	= new Student(1115,"Test5","City5",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student7	= new Student(1116,"Test6","City6",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student8	= new Student(1117,"Test7","City7",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student9	= new Student(1118,"Test8","City8",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student10	= new Student(1119,"Test9","City9",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student11	= new Student(1120,"Test10","City10",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student12	= new Student(1121,"Test11","City11",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student13	= new Student(1122,"Test12","City12",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student14	= new Student(1123,"Test13","City13",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student15	= new Student(1124,"Test14","City14",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student16	= new Student(1125,"Test15","City15",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student17	= new Student(1126,"Test16","City16",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student18	= new Student(1127,"Test17","City17",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student19	= new Student(1128,"Test18","City18",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student20	= new Student(1129,"Test19","City19",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student21	= new Student(1130,"Test20","City20",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student22	= new Student(1131,"Test21","City21",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student23	= new Student(1132,"Test22","City22",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student24	= new Student(1133,"Test23","City23",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student25	= new Student(1134,"Test24","City24",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student26	= new Student(1135,"Test25","City25",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student27	= new Student(1136,"Test26","City26",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student28	= new Student(1137,"Test27","City27",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student29	= new Student(1138,"Test28","City28",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student30	= new Student(1139,"Test29","City29",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student31	= new Student(1140,"Test30","City30",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student32	= new Student(1141,"Test31","City31",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student33	= new Student(1142,"Test32","City32",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student34	= new Student(1143,"Test33","City33",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student35	= new Student(1144,"Test34","City34",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student36	= new Student(1145,"Test35","City35",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student37	= new Student(1146,"Test36","City36",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student38	= new Student(1147,"Test37","City37",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student39	= new Student(1148,"Test38","City38",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student40	= new Student(1149,"Test39","City39",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student41	= new Student(1150,"Test40","City40",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student42	= new Student(1151,"Test41","City41",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student43	= new Student(1152,"Test42","City42",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student44	= new Student(1153,"Test43","City43",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student45	= new Student(1154,"Test44","City44",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student46	= new Student(1155,"Test45","City45",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student47	= new Student(1156,"Test46","City46",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student48	= new Student(1157,"Test47","City47",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student49	= new Student(1158,"Test48","City48",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student50	= new Student(1159,"Test49","City49",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student51	= new Student(1160,"Test50","City50",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student52	= new Student(1161,"Test51","City51",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student53	= new Student(1162,"Test52","City52",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student54	= new Student(1163,"Test53","City53",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student55	= new Student(1164,"Test54","City54",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student56	= new Student(1165,"Test55","City55",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student57	= new Student(1166,"Test56","City56",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student58	= new Student(1167,"Test57","City57",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student59	= new Student(1168,"Test58","City58",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student60	= new Student(1169,"Test59","City59",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student61	= new Student(1170,"Test60","City60",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student62	= new Student(1171,"Test61","City61",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student63	= new Student(1172,"Test62","City62",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student64	= new Student(1173,"Test63","City63",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student65	= new Student(1174,"Test64","City64",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student66	= new Student(1175,"Test65","City65",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student67	= new Student(1176,"Test66","City66",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student68	= new Student(1177,"Test67","City67",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student69	= new Student(1178,"Test68","City68",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student70	= new Student(1179,"Test69","City69",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student71	= new Student(1180,"Test70","City70",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student72	= new Student(1181,"Test71","City71",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student73	= new Student(1182,"Test72","City72",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student74	= new Student(1183,"Test73","City73",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student75	= new Student(1184,"Test74","City74",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student76	= new Student(1185,"Test75","City75",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student77	= new Student(1186,"Test76","City76",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student78	= new Student(1187,"Test77","City77",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student79	= new Student(1188,"Test78","City78",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student80	= new Student(1189,"Test79","City79",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student81	= new Student(1190,"Test80","City80",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student82	= new Student(1191,"Test81","City81",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student83	= new Student(1192,"Test82","City82",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student84	= new Student(1193,"Test83","City83",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student85	= new Student(1194,"Test84","City84",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student86	= new Student(1195,"Test85","City85",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student87	= new Student(1196,"Test86","City86",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student88	= new Student(1197,"Test87","City87",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student89	= new Student(1198,"Test88","City88",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student90	= new Student(1199,"Test89","City89",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student91	= new Student(1200,"Test90","City90",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student92	= new Student(1201,"Test91","City91",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student93	= new Student(1202,"Test92","City92",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student94	= new Student(1203,"Test93","City93",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student95	= new Student(1204,"Test94","City94",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student96	= new Student(1205,"Test95","City95",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student97	= new Student(1206,"Test96","City96",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student98	= new Student(1207,"Test97","City97",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student99	= new Student(1208,"Test98","City98",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student100	= new Student(1209,"Test99","City99",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student101	= new Student(1210,"Test100","City100",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student102	= new Student(1211,"Test101","City101",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student103	= new Student(1212,"Test102","City102",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student104	= new Student(1213,"Test103","City103",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student105	= new Student(1214,"Test104","City104",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student106	= new Student(1215,"Test105","City105",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student107	= new Student(1216,"Test106","City106",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student108	= new Student(1217,"Test107","City107",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student109	= new Student(1218,"Test108","City108",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student110	= new Student(1219,"Test109","City109",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student111	= new Student(1220,"Test110","City110",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student112	= new Student(1221,"Test111","City111",new Certificate("Bowling MasterClass", "3 Years"));
        Student	student113	= new Student(1222,"Test112","City112",new Certificate("Bowling MasterClass", "3 Years"));


        Session session = new Configuration().configure().buildSessionFactory().openSession();
        Transaction transaction = session.beginTransaction();

        session.save(student1);
        session.save(student2);
        session.save(student3);
        session.save(student4);
        session.save(student5);
        session.save(student6);
        session.save(student7);
        session.save(student8);
        session.save(student9);
        session.save(student10);
        session.save(student11);
        session.save(student12);
        session.save(student13);
        session.save(student14);
        session.save(student15);
        session.save(student16);
        session.save(student17);
        session.save(student18);
        session.save(student19);
        session.save(student20);
        session.save(student21);
        session.save(student22);
        session.save(student23);
        session.save(student24);
        session.save(student25);
        session.save(student26);
        session.save(student27);
        session.save(student28);
        session.save(student29);
        session.save(student30);
        session.save(student31);
        session.save(student32);
        session.save(student33);
        session.save(student34);
        session.save(student35);
        session.save(student36);
        session.save(student37);
        session.save(student38);
        session.save(student39);
        session.save(student40);
        session.save(student41);
        session.save(student42);
        session.save(student43);
        session.save(student44);
        session.save(student45);
        session.save(student46);
        session.save(student47);
        session.save(student48);
        session.save(student49);
        session.save(student50);
        session.save(student51);
        session.save(student52);
        session.save(student53);
        session.save(student54);
        session.save(student55);
        session.save(student56);
        session.save(student57);
        session.save(student58);
        session.save(student59);
        session.save(student60);
        session.save(student61);
        session.save(student62);
        session.save(student63);
        session.save(student64);
        session.save(student65);
        session.save(student66);
        session.save(student67);
        session.save(student68);
        session.save(student69);
        session.save(student70);
        session.save(student71);
        session.save(student72);
        session.save(student73);
        session.save(student74);
        session.save(student75);
        session.save(student76);
        session.save(student77);
        session.save(student78);
        session.save(student79);
        session.save(student80);
        session.save(student81);
        session.save(student82);
        session.save(student83);
        session.save(student84);
        session.save(student85);
        session.save(student86);
        session.save(student87);
        session.save(student88);
        session.save(student89);
        session.save(student90);
        session.save(student91);
        session.save(student92);
        session.save(student93);
        session.save(student94);
        session.save(student95);
        session.save(student96);
        session.save(student97);
        session.save(student98);
        session.save(student99);
        session.save(student100);
        session.save(student101);
        session.save(student102);
        session.save(student103);
        session.save(student104);
        session.save(student105);
        session.save(student106);
        session.save(student107);
        session.save(student108);
        session.save(student109);
        session.save(student110);
        session.save(student111);
        session.save(student112);
        session.save(student113);


        transaction.commit();
        session.close();


    }
}
